
CREATE TABLE REGIONS(
    REGION_ID NUMBER,
    REGION_NAME VARCHAR2(25)
);

CREATE TABLE COUNTRIES(
    COUNRIES_ID CHAR(2),
    COUNTY_NAME VARCHAR2(40),
    REGION_ID NUMBER
);

CREATE TABLE LOCATIONS(
    LOCATINON_ID NUMBER,
    STREET_ADRESS VARCHAR2(40),
    POSTAL_CODE VARCHAR2(12),
    CITY VARCHAR2(30)NOT NULL,
    STATE_PROVINCE VARCHAR2(25),
    COUNRIES_ID CHAR(2)
);

CREATE TABLE DEPARTMENTS(
    DEPARTMENT_ID NUMBER(2),
    DEPARTMANET_NAME VARCHAR2(49),
    MANAGER_ID NUMBER
);

CREATE TABLE JOBS(
    JOB_ID VARCHAR2(10),
    JOB_TITLE VARCHAR2(50) NOT NULL,
    MIN_SALARY NUMBER (6),
    MAX_SALARY NUMBER (6)  
);

CREATE TABLE EMPLOYEES(
    EMPLOYEES_ID NUMBER(6),
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    EMAIL VARCHAR2(40) NOT NULL,
    PHONE_NUMBER VARCHAR2(20),
    HIRE_DATE DATE NOT NULL,
    JOB_ID VARCHAR2(10),
    SALARY NUMBER(8,2),
    COMMISSION_PCT NUMBER(2,2),
    MANAGER_ID NUMBER(6),
    CONSTRAINT EMP_SALARY_MIN CHECK (SALARY > 0),
    CONSTRAINT EMP_EMAIL_UK UNIQUE (EMAIL)
);

CREATE TABLE JOB_HISTORY(
    EMPLOYEES_ID NUMBER(6),
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    JOB_ID VARCHAR2(10),
    DEPARTMENT_ID NUMBER(2),
    CONSTRAINT HIST_DATE_INTERVAL CHECK (END_DATE> START_DATE)
);


ALTER TABLE WARLORD.REGIONS ADD (
    CONSTRAINT reg_id_pk PRIMARY KEY (REGION_ID) 
);


ALTER TABLE WARLORD.COUNTRIES ADD (
    CONSTRAINT countr_reg_fk FOREIGN KEY (REGION_ID) REFERENCES REGIONS (REGION_ID)
);

ALTER TABLE WARLORD.COUNTRIES ADD (
    CONSTRAINT count_id_pk PRIMARY KEY (COUNRIES_ID)
);

ALTER TABLE WARLORD.LOCATIONS ADD(
     CONSTRAINT loca_pd_id PRIMARY KEY (LOCATINON_ID)
    ,CONSTRAINT loca_fk FOREIGN KEY(COUNRIES_ID) REFERENCES COUNTRIES (COUNRIES_ID)
);

ALTER TABLE WARLORD.DEPARTMENTS ADD (
    CONSTRAINT depa_id PRIMARY KEY (DEPARTMENT_ID),
    CONSTRAINT depa_loc_fk FOREIGN KEY (LOCATINON_ID) REFERENCES LOCATIONS (LOCATINON_ID)
);


ALTER TABLE WARLORD.DEPARTMENTS ADD LOCATINON_ID NUMBER;

ALTER TABLE WARLORD.JOBS ADD(
    CONSTRAINT job_id PRIMARY KEY (JOB_ID)
);

ALTER TABLE WARLORD.EMPLOYEES ADD DEPARTMENT_ID NUMBER(2);

ALTER TABLE WARLORD.EMPLOYEES ADD(
    CONSTRAINT emp_id PRIMARY KEY (EMPLOYEES_ID),
    CONSTRAINT emp_dp_fk FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID),
    CONSTRAINT emp_job_fk FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID),
    CONSTRAINT emp_departmens_fk FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID)
);

ALTER TABLE WARLORD.DEPARTMENTS MODIFY MANAGER_ID NUMBER(6);

ALTER TABLE DEPARTMENTS ADD (
    CONSTRAINT MAN_EM_FK FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID)
);

ALTER TABLE JOB_HISTORY ADD(
    CONSTRAINT job_pk PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT job_pd_fk FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID),
    CONSTRAINT emp_fk FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID),
    CONSTRAINT dep_fk FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID)
);
    --CONSTRAINT job_dep_fk FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID)
);

ALTER TABLE JOB_HISTORY RENAME  COLUMN EMPLOYEES_ID TO EMPLOYEE_ID

ALTER TABLE table_name RENAME COLUMN old_name TO new_name;





